server.port : 80
pet-clinic:
  host-name: my-pet.com
  name: Aibolit
  working-hours:
      start:  8AM
      end: 5PM
  doctors-specializations:  surgeon, veterinarian, therapeutist
spring:
  h2:
    console:
      enabled: true;